/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

/**
 *
 * @author admin
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Add_Category extends javax.swing.JFrame {

    /**
     * Creates new form Add_Category
     */
   

    Connection connection = null;

    //Statement statement = null;
    PreparedStatement pstm = null;

    
    public Add_Category() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        category_p1 = new javax.swing.JPanel();
        category_lbl_title = new javax.swing.JLabel();
        category_p2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        category_txt_name = new javax.swing.JTextField();
        category_btn_add = new javax.swing.JButton();
        category_btn_cancel = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Item category");
        setBackground(new java.awt.Color(255, 255, 204));

        category_p1.setBackground(new java.awt.Color(255, 255, 102));
        category_p1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        category_p1.setForeground(new java.awt.Color(255, 255, 102));

        category_lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        category_lbl_title.setText("Add Category");

        javax.swing.GroupLayout category_p1Layout = new javax.swing.GroupLayout(category_p1);
        category_p1.setLayout(category_p1Layout);
        category_p1Layout.setHorizontalGroup(
            category_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_p1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(category_lbl_title)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        category_p1Layout.setVerticalGroup(
            category_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(category_lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        category_p2.setBackground(new java.awt.Color(255, 255, 153));
        category_p2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        category_p2.setForeground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Name");

        category_txt_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        category_btn_add.setBackground(new java.awt.Color(255, 255, 51));
        category_btn_add.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        category_btn_add.setText("ADD");
        category_btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_btn_addActionPerformed(evt);
            }
        });

        category_btn_cancel.setBackground(new java.awt.Color(255, 255, 51));
        category_btn_cancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        category_btn_cancel.setText("Cancel");
        category_btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout category_p2Layout = new javax.swing.GroupLayout(category_p2);
        category_p2.setLayout(category_p2Layout);
        category_p2Layout.setHorizontalGroup(
            category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_p2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(category_btn_add))
                .addGroup(category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(category_p2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(category_btn_cancel))
                    .addGroup(category_p2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(category_txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        category_p2Layout.setVerticalGroup(
            category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(category_p2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(category_txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(category_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category_btn_add)
                    .addComponent(category_btn_cancel))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(category_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(category_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(category_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(category_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void category_btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_btn_addActionPerformed
        // TODO add your handling code here:
        
        //decleration
        String[] item_arr = new String[2];
        int countInserted = 0;
        
        //getting the value from form components
        //int category_id = Integer.parseInt(category_txt_id.getText());
        String category_name = category_txt_name.getText();
        
        //displaying the data
        //System.out.println("Categroy ID: - " + category_id);
        System.out.println("Category Name: - " + category_name);
        
        //Database 
        //insert operations
        try {

            connection = Conn.setConnect();
            //statement = connection.createStatement();

            //String sqlInsert = "INSERT INTO category(id,name) VALUES (4,'')";
            //String sqlInsert = "INSERT INTO category(id,name) VALUES (category_id,category_name)";
            String sqlInsert = "INSERT INTO `category` (name) VALUES (?)";

            PreparedStatement pstm = connection.prepareStatement(sqlInsert);

            //pstm.setInt(1, category_id);
            pstm.setString(1, category_name);
           
            System.out.println("The SQL statement is: " + sqlInsert + "\n");  // Echo for debugging
            countInserted = pstm.executeUpdate();
            System.out.println(countInserted + " records inserted.\n");

        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            try {
                connection.close();
                //statement.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_items.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //displaying the data into message dialog box
        //item_arr[0] = String.valueOf(category_id);
        item_arr[0] = category_name;
        item_arr[1] = countInserted + " records inserted successfully.\n";
        JOptionPane.showMessageDialog(this, item_arr);
        
        
    }//GEN-LAST:event_category_btn_addActionPerformed

    private void category_btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_btn_cancelActionPerformed

        Add_items obj = new Add_items();
        obj.setVisible(true);
        setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_category_btn_cancelActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton category_btn_add;
    private javax.swing.JButton category_btn_cancel;
    private javax.swing.JLabel category_lbl_title;
    private javax.swing.JPanel category_p1;
    private javax.swing.JPanel category_p2;
    private javax.swing.JTextField category_txt_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
