/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

/**
 *
 * @author admin
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class Bill_preview extends javax.swing.JFrame {

    /**
     * Creates new form bill_preview
     */
    
    Bill_item billitem = null;
    DefaultTableModel tblobj = null;
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public Bill_preview() {
        initComponents();
       
       setData();
       setTableContent(); 
       
       
       
       
    }
    
    
    void setData()
    {
        Bill_item billitems = new Bill_item();
        Bill_generate billgen = new Bill_generate();
        bill3_lbl_CusNm1.setText(billgen.cus_name);
        bill3_lbl_CusMob1.setText(billgen.cus_mobno);
        
        //database operation
        //fetching the value from bill_master
        
        //String query = "SELECT id,date FROM `bill_master` WHERE id="+billgen.cus_id;
        String query = "SELECT id,date FROM `bill_master` WHERE (customer_id="+billgen.cus_id+") AND (Total="+billitem.grandtotal+")";
        System.out.println("Query = "+query);
        try
        {
            conn = Conn.setConnect();
            stmt = conn.createStatement();
            System.out.println("1");
            rs = stmt.executeQuery(query);
            System.out.println("2");
            while(rs.next())
            {
                System.out.println(String.valueOf(rs.getInt("id")));
                bill3_lbl_billId1.setText( String.valueOf(rs.getInt("id")) );
                System.out.println(String.valueOf(rs.getDate("date")));
                bill3_lbl_billDate1.setText( String.valueOf(rs.getDate("date")) );
            }
            System.out.println("3");
            
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            try
            {
                stmt.close();
                conn.close();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        
        
        
        
    }
    
    void setTableContent()
    {
          billitem = new Bill_item();
         tblobj = new DefaultTableModel();
         bill3_tbl.setModel(tblobj);
        //DefaultTableModel tbl =  billitem.getmodel();
        String arr[][] =  Bill_item.arr;
        
        tblobj.addColumn("Sr No.");
        tblobj.addColumn("Product Name");
        tblobj.addColumn("Quantity");
        tblobj.addColumn("Price");
        tblobj.addColumn("Total Amount");
        
        
       for(int i=0;i<(billitem.SrNo);i++)
       {           
           //tblobj.insertRow(i, new Object[] {SrNo,product_name,qnttxt,amount,totalamt});
           tblobj.insertRow(i, new Object[] {arr[i][0],arr[i][1],arr[i][2],arr[i][3],arr[i][4]});        
       }
       
       bill3_lbl_gTotal1.setText(String.valueOf(billitem.grandtotal));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill3_p1 = new javax.swing.JPanel();
        bill3_lbl_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bill3_lbl_CusNm = new javax.swing.JLabel();
        bill3_lbl_billId = new javax.swing.JLabel();
        bill3_lbl_CusMob1 = new javax.swing.JLabel();
        bill3_lbl_billDate = new javax.swing.JLabel();
        bill3_lbl_CusNm1 = new javax.swing.JLabel();
        bill3_lbl_CusMob = new javax.swing.JLabel();
        bill3_lbl_billDate1 = new javax.swing.JLabel();
        bill3_lbl_billId1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill3_tbl = new javax.swing.JTable();
        bill3_p3 = new javax.swing.JPanel();
        bill3_btn_close = new javax.swing.JButton();
        bill3_lbl_gTotal = new javax.swing.JLabel();
        bill3_lbl_gTotal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill Preview");

        bill3_p1.setBackground(new java.awt.Color(255, 255, 102));
        bill3_p1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bill3_lbl_title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bill3_lbl_title.setText("BILL");

        javax.swing.GroupLayout bill3_p1Layout = new javax.swing.GroupLayout(bill3_p1);
        bill3_p1.setLayout(bill3_p1Layout);
        bill3_p1Layout.setHorizontalGroup(
            bill3_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill3_p1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(bill3_lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill3_p1Layout.setVerticalGroup(
            bill3_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill3_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill3_lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 204, 153));

        bill3_lbl_CusNm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_CusNm.setText("Customer Name: - ");

        bill3_lbl_billId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_billId.setText("Invoice No: - ");

        bill3_lbl_CusMob1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_CusMob1.setText("xxxxx-xxxxx");

        bill3_lbl_billDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_billDate.setText("Date: - ");

        bill3_lbl_CusNm1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_CusNm1.setText("Name");

        bill3_lbl_CusMob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_CusMob.setText("Contact No: - ");

        bill3_lbl_billDate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_billDate1.setText("dd-mm-yyyy");

        bill3_lbl_billId1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_lbl_billId1.setText("xx-00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(bill3_lbl_CusNm)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bill3_lbl_CusMob1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addComponent(bill3_lbl_billId)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bill3_lbl_CusNm1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bill3_lbl_billDate)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill3_lbl_billDate1)
                    .addComponent(bill3_lbl_billId1))
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(bill3_lbl_CusMob)
                    .addContainerGap(598, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bill3_lbl_CusNm)
                            .addComponent(bill3_lbl_CusNm1)
                            .addComponent(bill3_lbl_billDate1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bill3_lbl_billDate)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bill3_lbl_billId)
                            .addComponent(bill3_lbl_billId1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bill3_lbl_CusMob1)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(bill3_lbl_CusMob)
                    .addGap(36, 36, 36)))
        );

        bill3_tbl.setBackground(new java.awt.Color(255, 255, 204));
        bill3_tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bill3_tbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Product Name", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(bill3_tbl);

        bill3_p3.setBackground(new java.awt.Color(255, 255, 153));
        bill3_p3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bill3_btn_close.setBackground(new java.awt.Color(255, 255, 204));
        bill3_btn_close.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bill3_btn_close.setText("Close");

        bill3_lbl_gTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill3_lbl_gTotal.setText("Grand Total: - ");

        bill3_lbl_gTotal1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bill3_lbl_gTotal1.setText("0.0");

        javax.swing.GroupLayout bill3_p3Layout = new javax.swing.GroupLayout(bill3_p3);
        bill3_p3.setLayout(bill3_p3Layout);
        bill3_p3Layout.setHorizontalGroup(
            bill3_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill3_p3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(bill3_lbl_gTotal)
                .addGap(18, 18, 18)
                .addComponent(bill3_lbl_gTotal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bill3_btn_close)
                .addGap(43, 43, 43))
        );
        bill3_p3Layout.setVerticalGroup(
            bill3_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill3_p3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bill3_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill3_btn_close)
                    .addComponent(bill3_lbl_gTotal)
                    .addComponent(bill3_lbl_gTotal1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bill3_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(bill3_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bill3_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bill3_p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_preview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill3_btn_close;
    private javax.swing.JLabel bill3_lbl_CusMob;
    private javax.swing.JLabel bill3_lbl_CusMob1;
    private javax.swing.JLabel bill3_lbl_CusNm;
    private javax.swing.JLabel bill3_lbl_CusNm1;
    private javax.swing.JLabel bill3_lbl_billDate;
    private javax.swing.JLabel bill3_lbl_billDate1;
    private javax.swing.JLabel bill3_lbl_billId;
    private javax.swing.JLabel bill3_lbl_billId1;
    private javax.swing.JLabel bill3_lbl_gTotal;
    private javax.swing.JLabel bill3_lbl_gTotal1;
    private javax.swing.JLabel bill3_lbl_title;
    private javax.swing.JPanel bill3_p1;
    private javax.swing.JPanel bill3_p3;
    private javax.swing.JTable bill3_tbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
